// SpellMaster word bank.
// Each grade has ~30 words: { w: word, s: spoken example sentence, p: points }.
// Points reflect difficulty within the grade (10 easy, 15 medium, 20 hard, 25 challenge).
// Every sentence contains the word so the text-to-speech reads it in context
// (this also disambiguates homophones like "eight" vs "ate").

const WORD_BANK = {
  1: [
    { w: "cat", s: "The cat sat on my lap.", p: 10 },
    { w: "dog", s: "My dog likes to play fetch.", p: 10 },
    { w: "sun", s: "The sun is bright in the sky.", p: 10 },
    { w: "hat", s: "I wear a hat when it is cold.", p: 10 },
    { w: "run", s: "I like to run very fast.", p: 10 },
    { w: "big", s: "That is a big elephant.", p: 10 },
    { w: "red", s: "My favorite color is red.", p: 10 },
    { w: "cup", s: "I drink milk from a cup.", p: 10 },
    { w: "pen", s: "I write with a blue pen.", p: 10 },
    { w: "box", s: "The toys go in the box.", p: 10 },
    { w: "fish", s: "The fish swims in the tank.", p: 15 },
    { w: "jump", s: "Watch me jump over the rope.", p: 15 },
    { w: "milk", s: "I drink milk with my cookies.", p: 15 },
    { w: "hand", s: "Raise your hand to ask a question.", p: 15 },
    { w: "frog", s: "The frog hopped into the pond.", p: 15 },
    { w: "stop", s: "Please stop at the red light.", p: 15 },
    { w: "wind", s: "The wind blew my kite high.", p: 15 },
    { w: "sock", s: "I lost one sock in the laundry.", p: 15 },
    { w: "ship", s: "The ship sailed across the ocean.", p: 15 },
    { w: "nest", s: "The bird built a nest in the tree.", p: 15 },
    { w: "tree", s: "We climbed the tall tree.", p: 20 },
    { w: "rain", s: "The rain made puddles outside.", p: 20 },
    { w: "book", s: "Read me a book before bed.", p: 20 },
    { w: "play", s: "Let's play in the park.", p: 20 },
    { w: "green", s: "The grass is green in spring.", p: 20 },
    { w: "sleep", s: "I sleep with my teddy bear.", p: 20 },
    { w: "black", s: "The night sky is black.", p: 20 },
    { w: "snow", s: "We made a snowman in the snow.", p: 20 },
    { w: "house", s: "My house has a red door.", p: 25 },
    { w: "train", s: "The train goes down the tracks.", p: 25 },
  ],
  2: [
    { w: "bird", s: "The bird sang a pretty song.", p: 10 },
    { w: "cake", s: "We ate cake at the party.", p: 10 },
    { w: "ride", s: "I ride my bike to school.", p: 10 },
    { w: "line", s: "Please stand in a straight line.", p: 10 },
    { w: "home", s: "We went home after the game.", p: 10 },
    { w: "game", s: "Let's play a board game.", p: 10 },
    { w: "blue", s: "The sky is blue today.", p: 10 },
    { w: "flag", s: "The flag waves in the wind.", p: 10 },
    { w: "swim", s: "I love to swim in the pool.", p: 10 },
    { w: "king", s: "The king lived in a castle.", p: 10 },
    { w: "plant", s: "We plant seeds in the garden.", p: 15 },
    { w: "smile", s: "Your smile makes me happy.", p: 15 },
    { w: "stone", s: "I skipped a stone across the lake.", p: 15 },
    { w: "brave", s: "The brave firefighter saved the cat.", p: 15 },
    { w: "chair", s: "Please sit in your chair.", p: 15 },
    { w: "sharp", s: "Be careful, that knife is sharp.", p: 15 },
    { w: "queen", s: "The queen wore a golden crown.", p: 15 },
    { w: "dream", s: "I had a funny dream last night.", p: 15 },
    { w: "snack", s: "Apples make a healthy snack.", p: 15 },
    { w: "cloud", s: "That cloud looks like a bunny.", p: 15 },
    { w: "happy", s: "I feel happy on my birthday.", p: 20 },
    { w: "water", s: "Drink water when you are thirsty.", p: 20 },
    { w: "sister", s: "My sister is older than me.", p: 20 },
    { w: "summer", s: "We go to the beach in summer.", p: 20 },
    { w: "paper", s: "Draw a picture on the paper.", p: 20 },
    { w: "story", s: "Grandpa told us a funny story.", p: 20 },
    { w: "party", s: "We had pizza at the party.", p: 20 },
    { w: "teacher", s: "My teacher reads to us every day.", p: 20 },
    { w: "animal", s: "A zebra is a striped animal.", p: 25 },
    { w: "candle", s: "She blew out the candle on the cake.", p: 25 },
  ],
  3: [
    { w: "light", s: "Turn on the light, it is dark.", p: 10 },
    { w: "money", s: "I saved my money in a jar.", p: 10 },
    { w: "night", s: "The stars come out at night.", p: 10 },
    { w: "north", s: "The compass points north.", p: 10 },
    { w: "baby", s: "The baby laughed at the puppy.", p: 10 },
    { w: "lunch", s: "We eat lunch at noon.", p: 10 },
    { w: "street", s: "Look both ways before crossing the street.", p: 10 },
    { w: "teeth", s: "Brush your teeth before bed.", p: 10 },
    { w: "plane", s: "The plane flew above the clouds.", p: 10 },
    { w: "month", s: "June is my favorite month.", p: 10 },
    { w: "pencil", s: "I sharpened my pencil before the test.", p: 15 },
    { w: "circle", s: "Draw a circle around the answer.", p: 15 },
    { w: "friend", s: "My best friend lives next door.", p: 15 },
    { w: "young", s: "The young puppy chewed my shoe.", p: 15 },
    { w: "eight", s: "I have eight crayons in my box.", p: 15 },
    { w: "world", s: "I want to travel around the world.", p: 15 },
    { w: "earth", s: "The earth goes around the sun.", p: 15 },
    { w: "mouth", s: "Cover your mouth when you sneeze.", p: 15 },
    { w: "carry", s: "Help me carry the groceries inside.", p: 15 },
    { w: "ocean", s: "Whales live in the ocean.", p: 15 },
    { w: "because", s: "I smiled because the joke was funny.", p: 20 },
    { w: "people", s: "Many people came to the parade.", p: 20 },
    { w: "follow", s: "Please follow the trail signs.", p: 20 },
    { w: "listen", s: "Listen carefully to the directions.", p: 20 },
    { w: "picture", s: "I drew a picture of my family.", p: 20 },
    { w: "family", s: "My family eats dinner together.", p: 20 },
    { w: "present", s: "I wrapped a present for my friend.", p: 20 },
    { w: "hungry", s: "The hungry bear looked for berries.", p: 20 },
    { w: "butterfly", s: "A butterfly landed on the flower.", p: 25 },
    { w: "sandwich", s: "I packed a turkey sandwich for lunch.", p: 25 },
  ],
  4: [
    { w: "finish", s: "Please finish your homework first.", p: 10 },
    { w: "market", s: "We bought fruit at the market.", p: 10 },
    { w: "garden", s: "Tomatoes grow in our garden.", p: 10 },
    { w: "second", s: "She finished the race in second place.", p: 10 },
    { w: "contest", s: "I won the spelling contest.", p: 10 },
    { w: "pretty", s: "The sunset was pretty tonight.", p: 10 },
    { w: "bridge", s: "We walked across the old bridge.", p: 10 },
    { w: "orange", s: "I peeled an orange for a snack.", p: 10 },
    { w: "magic", s: "The magician did a magic trick.", p: 10 },
    { w: "simple", s: "The recipe is simple to follow.", p: 10 },
    { w: "question", s: "Raise your hand if you have a question.", p: 15 },
    { w: "holiday", s: "My favorite holiday is in the winter.", p: 15 },
    { w: "machine", s: "The washing machine is very loud.", p: 15 },
    { w: "special", s: "Today is a special day for our class.", p: 15 },
    { w: "problem", s: "We solved the math problem together.", p: 15 },
    { w: "address", s: "Write your address on the envelope.", p: 15 },
    { w: "balloon", s: "The red balloon floated away.", p: 15 },
    { w: "captain", s: "The captain steered the ship safely.", p: 15 },
    { w: "journey", s: "Their journey across the desert took weeks.", p: 15 },
    { w: "library", s: "I borrowed three books from the library.", p: 15 },
    { w: "important", s: "It is important to be kind.", p: 20 },
    { w: "surprise", s: "The party was a wonderful surprise.", p: 20 },
    { w: "remember", s: "Remember to feed the goldfish.", p: 20 },
    { w: "although", s: "Although it rained, we still had fun.", p: 20 },
    { w: "daughter", s: "Their daughter plays the violin.", p: 20 },
    { w: "favorite", s: "Pizza is my favorite food.", p: 20 },
    { w: "medicine", s: "The doctor gave me medicine for my cough.", p: 20 },
    { w: "mountain", s: "We hiked up the tall mountain.", p: 20 },
    { w: "beautiful", s: "The garden looks beautiful in spring.", p: 25 },
    { w: "knowledge", s: "Reading books gives you knowledge.", p: 25 },
  ],
  5: [
    { w: "chapter", s: "We read one chapter every night.", p: 10 },
    { w: "message", s: "I left a message on the board.", p: 10 },
    { w: "freedom", s: "The bird flew to freedom.", p: 10 },
    { w: "kitchen", s: "Dinner smells great in the kitchen.", p: 10 },
    { w: "planet", s: "Mars is called the red planet.", p: 10 },
    { w: "soccer", s: "We played soccer after school.", p: 10 },
    { w: "modern", s: "The museum has modern art.", p: 10 },
    { w: "towel", s: "Dry your hands with a towel.", p: 10 },
    { w: "prize", s: "She won first prize at the fair.", p: 10 },
    { w: "engine", s: "The train engine roared to life.", p: 10 },
    { w: "against", s: "We played against the best team.", p: 15 },
    { w: "ancient", s: "The ancient pyramids are in Egypt.", p: 15 },
    { w: "climate", s: "The desert has a dry climate.", p: 15 },
    { w: "costume", s: "I wore a pirate costume on Halloween.", p: 15 },
    { w: "courage", s: "It takes courage to try new things.", p: 15 },
    { w: "distance", s: "We ran a long distance today.", p: 15 },
    { w: "harvest", s: "Farmers harvest the corn in fall.", p: 15 },
    { w: "journal", s: "I write in my journal every day.", p: 15 },
    { w: "mirror", s: "I saw my reflection in the mirror.", p: 15 },
    { w: "throne", s: "The king sat on his golden throne.", p: 15 },
    { w: "exercise", s: "Daily exercise keeps you strong.", p: 20 },
    { w: "island", s: "The boat landed on a small island.", p: 20 },
    { w: "weight", s: "The vet checked the puppy's weight.", p: 20 },
    { w: "straight", s: "Draw a straight line with a ruler.", p: 20 },
    { w: "tongue", s: "The dog licked me with its tongue.", p: 20 },
    { w: "calendar", s: "Mark the date on the calendar.", p: 20 },
    { w: "stomach", s: "My stomach growled before lunch.", p: 20 },
    { w: "whistle", s: "The coach blew the whistle to start the game.", p: 20 },
    { w: "neighbor", s: "Our neighbor waters our plants on vacation.", p: 25 },
    { w: "scissors", s: "Use scissors to cut along the line.", p: 25 },
  ],
  6: [
    { w: "launch", s: "We watched the rocket launch on TV.", p: 10 },
    { w: "member", s: "She is a member of the chess club.", p: 10 },
    { w: "palace", s: "The palace had a hundred rooms.", p: 10 },
    { w: "public", s: "The public pool opens in June.", p: 10 },
    { w: "reward", s: "There is a reward for the lost dog.", p: 10 },
    { w: "talent", s: "Singing is her special talent.", p: 10 },
    { w: "tunnel", s: "The train sped through the tunnel.", p: 10 },
    { w: "narrow", s: "The path was too narrow for bikes.", p: 10 },
    { w: "defend", s: "The goalie must defend the net.", p: 10 },
    { w: "volume", s: "Please turn down the volume.", p: 10 },
    { w: "autumn", s: "The leaves turn orange in autumn.", p: 15 },
    { w: "fierce", s: "The fierce storm shook the windows.", p: 15 },
    { w: "glacier", s: "The glacier moved slowly down the valley.", p: 15 },
    { w: "muscle", s: "Swimming builds muscle strength.", p: 15 },
    { w: "oxygen", s: "Plants release oxygen into the air.", p: 15 },
    { w: "rhythm", s: "Clap along with the rhythm of the song.", p: 15 },
    { w: "salmon", s: "The bear caught a salmon in the river.", p: 15 },
    { w: "system", s: "The solar system has eight planets.", p: 15 },
    { w: "theory", s: "The scientist tested her theory.", p: 15 },
    { w: "wrestle", s: "The kids like to wrestle on the mat.", p: 15 },
    { w: "achieve", s: "Work hard to achieve your goals.", p: 20 },
    { w: "anxious", s: "I was anxious before the big test.", p: 20 },
    { w: "athlete", s: "The athlete trained every morning.", p: 20 },
    { w: "echoes", s: "Our shouts made echoes in the canyon.", p: 20 },
    { w: "foreign", s: "She speaks two foreign languages.", p: 20 },
    { w: "genuine", s: "His apology was genuine and kind.", p: 20 },
    { w: "license", s: "Mom renewed her driving license.", p: 20 },
    { w: "receive", s: "Did you receive my letter?", p: 20 },
    { w: "mysterious", s: "A mysterious package arrived at the door.", p: 25 },
    { w: "vegetable", s: "Broccoli is my least favorite vegetable.", p: 25 },
  ],
  7: [
    { w: "ballot", s: "Each voter filled out a ballot.", p: 10 },
    { w: "campaign", s: "The mayor ran a long campaign.", p: 10 },
    { w: "deceive", s: "Magicians deceive the eye with quick hands.", p: 10 },
    { w: "fatigue", s: "After the marathon she felt deep fatigue.", p: 10 },
    { w: "hazard", s: "Ice on the road is a winter hazard.", p: 10 },
    { w: "leisure", s: "He reads novels in his leisure time.", p: 10 },
    { w: "negotiate", s: "The teams will negotiate a trade.", p: 10 },
    { w: "obstacle", s: "The fallen tree was an obstacle on the trail.", p: 10 },
    { w: "permanent", s: "The marker leaves a permanent stain.", p: 10 },
    { w: "summary", s: "Write a summary of the chapter.", p: 10 },
    { w: "definitely", s: "I will definitely come to your game.", p: 15 },
    { w: "separate", s: "Please separate the recycling from the trash.", p: 15 },
    { w: "privilege", s: "Driving is a privilege, not a right.", p: 15 },
    { w: "boundary", s: "The fence marks the property boundary.", p: 15 },
    { w: "curiosity", s: "Her curiosity led her to study insects.", p: 15 },
    { w: "desperate", s: "The team made a desperate final play.", p: 15 },
    { w: "embarrass", s: "Don't embarrass me in front of my friends.", p: 15 },
    { w: "frequency", s: "The radio station changed its frequency.", p: 15 },
    { w: "guarantee", s: "The store offers a money-back guarantee.", p: 15 },
    { w: "influence", s: "Good coaches influence their players.", p: 15 },
    { w: "acknowledge", s: "Please acknowledge that you heard me.", p: 20 },
    { w: "apparent", s: "The reason for the delay became apparent.", p: 20 },
    { w: "committee", s: "The committee meets every Tuesday.", p: 20 },
    { w: "conscious", s: "She made a conscious effort to be patient.", p: 20 },
    { w: "criticize", s: "It is easy to criticize and hard to create.", p: 20 },
    { w: "noticeable", s: "There was a noticeable change in the weather.", p: 20 },
    { w: "occasion", s: "Graduation is a special occasion.", p: 20 },
    { w: "persuade", s: "She tried to persuade us to stay longer.", p: 20 },
    { w: "questionnaire", s: "Fill out the questionnaire honestly.", p: 25 },
    { w: "rehearsal", s: "The band has rehearsal after school.", p: 25 },
  ],
  8: [
    { w: "abundant", s: "The valley had abundant wildflowers.", p: 10 },
    { w: "candidate", s: "Each candidate gave a short speech.", p: 10 },
    { w: "dialogue", s: "The play's dialogue was very funny.", p: 10 },
    { w: "emphasis", s: "The coach put emphasis on teamwork.", p: 10 },
    { w: "gauge", s: "Check the fuel gauge before the trip.", p: 10 },
    { w: "hesitate", s: "Don't hesitate to ask for help.", p: 10 },
    { w: "initial", s: "My initial guess turned out to be right.", p: 10 },
    { w: "luxury", s: "The hotel room was pure luxury.", p: 10 },
    { w: "pursue", s: "She wants to pursue a career in medicine.", p: 10 },
    { w: "vacuum", s: "Please vacuum the living room carpet.", p: 10 },
    { w: "amateur", s: "The amateur astronomer found a comet.", p: 15 },
    { w: "bureau", s: "The weather bureau issued a warning.", p: 15 },
    { w: "colonel", s: "The colonel saluted the troops.", p: 15 },
    { w: "courteous", s: "The waiter was courteous and quick.", p: 15 },
    { w: "exaggerate", s: "Fishermen tend to exaggerate the size of their catch.", p: 15 },
    { w: "grievance", s: "The workers filed a formal grievance.", p: 15 },
    { w: "illiterate", s: "The program helps illiterate adults learn to read.", p: 15 },
    { w: "jeopardy", s: "The late goal put their lead in jeopardy.", p: 15 },
    { w: "legitimate", s: "She had a legitimate excuse for being late.", p: 15 },
    { w: "maneuver", s: "The pilot performed a difficult maneuver.", p: 15 },
    { w: "conscience", s: "His conscience would not let him lie.", p: 20 },
    { w: "occurrence", s: "Rain is a rare occurrence in the desert.", p: 20 },
    { w: "pamphlet", s: "The museum handed out a free pamphlet.", p: 20 },
    { w: "parallel", s: "Train tracks run parallel to each other.", p: 20 },
    { w: "perseverance", s: "Perseverance helped her finish the novel.", p: 20 },
    { w: "playwright", s: "The playwright wrote a new comedy.", p: 20 },
    { w: "prejudice", s: "The judge set aside all prejudice.", p: 20 },
    { w: "sergeant", s: "The sergeant trained the new recruits.", p: 20 },
    { w: "miscellaneous", s: "The drawer was full of miscellaneous items.", p: 25 },
    { w: "silhouette", s: "We saw the silhouette of a hawk against the sunset.", p: 25 },
  ],
  9: [
    { w: "adjacent", s: "The park is adjacent to the school.", p: 10 },
    { w: "bizarre", s: "The movie had a bizarre ending.", p: 10 },
    { w: "chronological", s: "List the events in chronological order.", p: 10 },
    { w: "dilemma", s: "Choosing between the two offers was a dilemma.", p: 10 },
    { w: "eligible", s: "Seniors are eligible for the scholarship.", p: 10 },
    { w: "fluorescent", s: "The fluorescent lights hummed overhead.", p: 10 },
    { w: "gourmet", s: "He cooked a gourmet meal for the family.", p: 10 },
    { w: "hypocrite", s: "A hypocrite says one thing and does another.", p: 10 },
    { w: "intermediate", s: "She moved up to the intermediate swim class.", p: 10 },
    { w: "mediocre", s: "The critics called the film mediocre.", p: 10 },
    { w: "acquaintance", s: "He is an acquaintance from summer camp.", p: 15 },
    { w: "anonymous", s: "An anonymous donor paid for the new gym.", p: 15 },
    { w: "camouflage", s: "The lizard's camouflage hid it from hawks.", p: 15 },
    { w: "catastrophe", s: "The flood was a catastrophe for the town.", p: 15 },
    { w: "censorship", s: "The editorial argued against censorship.", p: 15 },
    { w: "controversy", s: "The new rule caused a big controversy.", p: 15 },
    { w: "exhilarating", s: "The roller coaster ride was exhilarating.", p: 15 },
    { w: "indispensable", s: "A good dictionary is indispensable for writers.", p: 15 },
    { w: "lieutenant", s: "The lieutenant reported to the captain.", p: 15 },
    { w: "pneumonia", s: "He stayed home for a week with pneumonia.", p: 15 },
    { w: "bureaucracy", s: "The permit was delayed by bureaucracy.", p: 20 },
    { w: "conscientious", s: "She is a conscientious student who checks her work.", p: 20 },
    { w: "embarrassment", s: "He blushed with embarrassment.", p: 20 },
    { w: "extraordinary", s: "The gymnast showed extraordinary balance.", p: 20 },
    { w: "inevitable", s: "After weeks of drought, water limits were inevitable.", p: 20 },
    { w: "maintenance", s: "The elevator is closed for maintenance.", p: 20 },
    { w: "pseudonym", s: "The author wrote under a pseudonym.", p: 20 },
    { w: "vengeance", s: "The knight swore vengeance against the dragon.", p: 20 },
    { w: "entrepreneur", s: "The young entrepreneur started a dog-walking business.", p: 25 },
    { w: "reconnaissance", s: "The scouts flew a reconnaissance mission.", p: 25 },
  ],
  10: [
    { w: "aesthetic", s: "The gallery has a minimalist aesthetic.", p: 10 },
    { w: "alleviate", s: "The medicine helped alleviate the pain.", p: 10 },
    { w: "benevolent", s: "The benevolent stranger paid for our meal.", p: 10 },
    { w: "cynical", s: "Don't be so cynical about people's motives.", p: 10 },
    { w: "eloquent", s: "Her eloquent speech moved the audience.", p: 10 },
    { w: "facetious", s: "His facetious remark broke the tension.", p: 10 },
    { w: "gregarious", s: "The gregarious host greeted every guest.", p: 10 },
    { w: "meticulous", s: "The jeweler did meticulous work.", p: 10 },
    { w: "nonchalant", s: "He gave a nonchalant shrug at the news.", p: 10 },
    { w: "pragmatic", s: "She took a pragmatic approach to the budget.", p: 10 },
    { w: "ambiguous", s: "The poem's ending is deliberately ambiguous.", p: 15 },
    { w: "belligerent", s: "The belligerent customer demanded a refund.", p: 15 },
    { w: "clairvoyant", s: "The clairvoyant claimed to see the future.", p: 15 },
    { w: "connoisseur", s: "My uncle is a connoisseur of fine cheese.", p: 15 },
    { w: "ubiquitous", s: "Smartphones have become ubiquitous.", p: 15 },
    { w: "incandescent", s: "The incandescent bulb glowed warmly.", p: 15 },
    { w: "juxtaposition", s: "The photo showed a juxtaposition of old and new.", p: 15 },
    { w: "kaleidoscope", s: "The festival was a kaleidoscope of colors.", p: 15 },
    { w: "labyrinth", s: "The old city was a labyrinth of alleys.", p: 15 },
    { w: "mnemonic", s: "She used a mnemonic to remember the planets.", p: 15 },
    { w: "acquiesce", s: "He had to acquiesce to the committee's decision.", p: 20 },
    { w: "dichotomy", s: "There is a dichotomy between theory and practice.", p: 20 },
    { w: "ephemeral", s: "Cherry blossoms are beautiful but ephemeral.", p: 20 },
    { w: "hierarchy", s: "Wolves have a strict social hierarchy.", p: 20 },
    { w: "iridescent", s: "The hummingbird's feathers were iridescent.", p: 20 },
    { w: "perfunctory", s: "He gave the report a perfunctory glance.", p: 20 },
    { w: "rendezvous", s: "The climbers set a rendezvous at base camp.", p: 20 },
    { w: "sycophant", s: "The king was surrounded by sycophants.", p: 20 },
    { w: "hors d'oeuvre", s: "Each guest took an hors d'oeuvre from the tray.", p: 25 },
    { w: "onomatopoeia", s: "Buzz and hiss are examples of onomatopoeia.", p: 25 },
  ],
  11: [
    { w: "abrogate", s: "The treaty was abrogated; to abrogate is to repeal.", p: 10 },
    { w: "cacophony", s: "A cacophony of horns filled the street.", p: 10 },
    { w: "deleterious", s: "Smoking has deleterious effects on health.", p: 10 },
    { w: "ebullient", s: "The ebullient fans stormed the field.", p: 10 },
    { w: "fastidious", s: "The fastidious editor caught every typo.", p: 10 },
    { w: "garrulous", s: "The garrulous barber told endless stories.", p: 10 },
    { w: "hegemony", s: "The empire held hegemony over the region.", p: 10 },
    { w: "iconoclast", s: "The iconoclast challenged every tradition.", p: 10 },
    { w: "lugubrious", s: "The hound had a lugubrious expression.", p: 10 },
    { w: "obsequious", s: "The obsequious clerk flattered every customer.", p: 10 },
    { w: "anachronism", s: "A wristwatch in a medieval film is an anachronism.", p: 15 },
    { w: "circumlocution", s: "His circumlocution avoided a direct answer.", p: 15 },
    { w: "disenfranchise", s: "The law would disenfranchise rural voters.", p: 15 },
    { w: "egregious", s: "The referee missed an egregious foul.", p: 15 },
    { w: "exacerbate", s: "Scratching will exacerbate the rash.", p: 15 },
    { w: "grandiloquent", s: "The senator's grandiloquent speech ran long.", p: 15 },
    { w: "idiosyncrasy", s: "Humming while working is her idiosyncrasy.", p: 15 },
    { w: "magnanimous", s: "The champion was magnanimous in victory.", p: 15 },
    { w: "obfuscate", s: "Jargon can obfuscate a simple idea.", p: 15 },
    { w: "perspicacious", s: "The perspicacious detective noticed the clue.", p: 15 },
    { w: "quintessential", s: "The corner diner is the quintessential American restaurant.", p: 20 },
    { w: "recalcitrant", s: "The recalcitrant mule refused to move.", p: 20 },
    { w: "sesquipedalian", s: "His sesquipedalian vocabulary impressed the judges.", p: 20 },
    { w: "surreptitious", s: "She cast a surreptitious glance at the clock.", p: 20 },
    { w: "tergiversation", s: "The politician's tergiversation frustrated reporters.", p: 20 },
    { w: "unconscionable", s: "Charging that price is unconscionable.", p: 20 },
    { w: "vicissitude", s: "He endured every vicissitude of fortune.", p: 20 },
    { w: "verisimilitude", s: "The novel's details give it verisimilitude.", p: 20 },
    { w: "pulchritudinous", s: "The pulchritudinous garden won first prize.", p: 25 },
    { w: "antediluvian", s: "Grandpa's antediluvian computer still runs.", p: 25 },
  ],
  12: [
    { w: "apocryphal", s: "The story about the cherry tree is apocryphal.", p: 10 },
    { w: "bowdlerize", s: "Editors chose to bowdlerize the old novel.", p: 10 },
    { w: "demagogue", s: "The demagogue stirred the crowd with fear.", p: 10 },
    { w: "ennui", s: "A long winter filled him with ennui.", p: 10 },
    { w: "flibbertigibbet", s: "The flibbertigibbet chattered through the lecture.", p: 10 },
    { w: "gerrymander", s: "The legislature tried to gerrymander the district.", p: 10 },
    { w: "histrionic", s: "Her histrionic sigh fooled no one.", p: 10 },
    { w: "insouciant", s: "He strolled in with an insouciant grin.", p: 10 },
    { w: "kowtow", s: "She refused to kowtow to the critics.", p: 10 },
    { w: "louche", s: "The detective questioned the louche nightclub owner.", p: 10 },
    { w: "machiavellian", s: "The villain's machiavellian plot unraveled.", p: 15 },
    { w: "nonpareil", s: "As a violinist she is nonpareil.", p: 15 },
    { w: "obstreperous", s: "The obstreperous parrot drowned out the meeting.", p: 15 },
    { w: "palimpsest", s: "The monks reused the palimpsest for new texts.", p: 15 },
    { w: "quixotic", s: "His quixotic plan was to sail around the world in a dinghy.", p: 15 },
    { w: "rapprochement", s: "The two nations reached a rapprochement.", p: 15 },
    { w: "schadenfreude", s: "He felt a guilty schadenfreude when the rival team lost.", p: 15 },
    { w: "terpsichorean", s: "Her terpsichorean talent lit up the stage.", p: 15 },
    { w: "umbrage", s: "She took umbrage at the rude remark.", p: 15 },
    { w: "vituperative", s: "The review was harsh and vituperative.", p: 15 },
    { w: "weltanschauung", s: "Travel broadened his weltanschauung.", p: 20 },
    { w: "xenophobia", s: "The editorial condemned xenophobia.", p: 20 },
    { w: "yoke", s: "The oxen pulled together under one yoke.", p: 20 },
    { w: "zeitgeist", s: "The film captured the zeitgeist of the sixties.", p: 20 },
    { w: "perspicuity", s: "She explained the theorem with perspicuity.", p: 20 },
    { w: "legerdemain", s: "The magician's legerdemain amazed the children.", p: 20 },
    { w: "prestidigitation", s: "His prestidigitation made the coin vanish.", p: 20 },
    { w: "sphygmomanometer", s: "The nurse used a sphygmomanometer to check blood pressure.", p: 20 },
    { w: "antidisestablishmentarianism", s: "Antidisestablishmentarianism is famously hard to spell.", p: 25 },
    { w: "floccinaucinihilipilification", s: "Floccinaucinihilipilification means treating something as worthless.", p: 25 },
  ],
};
